version: '3.6'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  pgweb:
    image: sosedoff/pgweb
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable
    ports:
      - "8091:8081"
  api:
    build: .
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: "Host=postgres; Username=postgres; Database=postgres; Pooling=true;"
    ports:
      - "8080:80"
